name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
        if: matrix.os == 'ubuntu-latest'
      - run: pnpm test:types
        if: matrix.os == 'ubuntu-latest'
      - run: pnpm build
        if: matrix.os == 'ubuntu-latest'
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v5
