name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
        if: matrix.os == 'ubuntu-latest'
      - run: pnpm test:types
        if: matrix.os == 'ubuntu-latest'
      - run: pnpm build
        if: matrix.os == 'ubuntu-latest'
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v5
